// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mAVizk5UV2DMPNe8DKlAaBCo-fSiL7E',
    appId: '1:907272246902:android:84829e63f2c29a72b9f157',
    messagingSenderId: '907272246902',
    projectId: 'ecomp2-9df5f',
    storageBucket: 'ecomp2-9df5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-fVpzogLo7dNe6COPGhqswV_nTv5dTPY',
    appId: '1:907272246902:ios:181102ba5ba6601cb9f157',
    messagingSenderId: '907272246902',
    projectId: 'ecomp2-9df5f',
    storageBucket: 'ecomp2-9df5f.appspot.com',
    iosBundleId: 'com.example.bazarmela',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4JjqyI1UITcQXkFqdD6YukKddjlrd1Y',
    appId: '1:907272246902:web:60f30bc421b0403bb9f157',
    messagingSenderId: '907272246902',
    projectId: 'ecomp2-9df5f',
    authDomain: 'ecomp2-9df5f.firebaseapp.com',
    storageBucket: 'ecomp2-9df5f.appspot.com',
    measurementId: 'G-66P9S7SYW4',
  );

}